"""Remove internal field identifiers and normalize criterion labels in paper prose."""

from __future__ import annotations

import re

_PROTECTED_BLOCK_RE = re.compile(
    r"(```[\s\S]*?```|~~~[\s\S]*?~~~|\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\])"
)

_DIRECTION_LABELS = {
    "极大型": "正向指标",
    "极小型": "负向指标",
    "中间型": "适中型指标",
    "区间型": "区间型指标",
}

# Internal score-column names generated by data processing, for example SC_1S.
_INTERNAL_SCORE_CODE_RE = re.compile(r"(?<![A-Za-z0-9_])SC_[A-Za-z0-9_]+(?![A-Za-z0-9_])")


def _clean_prose_segment(segment: str) -> str:
    cleaned = segment
    for raw, readable in _DIRECTION_LABELS.items():
        cleaned = cleaned.replace(raw, readable)

    # Remove an internal score code only when it is attached to a Chinese metric name.
    # This keeps the same token intact inside formulas and code blocks.
    cleaned = re.sub(
        r"(?<=[\u4e00-\u9fff])\s+SC_[A-Za-z0-9_]+(?![A-Za-z0-9_])",
        "",
        cleaned,
    )

    # Handle Markdown emphasis where the metric name and code are split by markup.
    cleaned = re.sub(
        r"(?<=[\u4e00-\u9fff])(?:\s|\*|_)*SC_[A-Za-z0-9_]+(?=(?:\*|_)*\s*[（(：:，,；;。])",
        "",
        cleaned,
    )

    # If the code is repeated directly before criterion metadata, remove it as well.
    cleaned = re.sub(
        r"\bSC_[A-Za-z0-9_]+\b\s*(?=[（(](?:正向指标|负向指标|适中型指标|区间型指标|单位|无量纲))",
        "",
        cleaned,
    )

    cleaned = re.sub(r"[ \t]+([（(：:，,；;。])", r"\1", cleaned)
    cleaned = re.sub(r"（\s*，", "（", cleaned)
    cleaned = re.sub(r"（\s*）", "", cleaned)
    return cleaned


def clean_internal_metric_labels(text: str) -> str:
    """Clean internal metric codes in narrative text while preserving formulas/code."""
    if not text:
        return ""

    parts = _PROTECTED_BLOCK_RE.split(text)
    output: list[str] = []
    for part in parts:
        if not part:
            continue
        if _PROTECTED_BLOCK_RE.fullmatch(part):
            output.append(part)
        else:
            output.append(_clean_prose_segment(part))

    cleaned = "".join(output)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned
