import type { WorkflowStage } from "./types";

export const WORKFLOW_STAGES: WorkflowStage[] = [
  {
    id: "00-intake",
    index: 0,
    title: "题目与附件盘点",
    shortTitle: "输入盘点",
    status: "READY",
    summary: "盘点题目、附件、依赖和缺失项。",
    inputs: ["题目文件与数据附件", "用户消息中的赛事、语言和交付要求"],
    outputs: ["RUN_CONTEXT.json", "INPUT_INVENTORY.json", "CAPABILITY_REPORT.json", "TASK_CHECKLIST.md", "STAGE_STATE.json"],
    acceptance: ["题目来源已确认", "全部附件已盘点", "缺失项已明确记录", "没有未解释的阻塞"],
  },
  {
    id: "01-analysis",
    index: 1,
    title: "赛题分析",
    shortTitle: "拆题分析",
    status: "LOCKED",
    summary: "逐句拆解题目事实、子问题、目标和约束。",
    inputs: ["00 阶段产物", "题目文本与附件摘要"],
    outputs: ["PROBLEM_ANALYSIS.md", "PROBLEM_FACTS.json", "CAPABILITY_CHECKLIST.json", "DATA_PROFILE.json（适用时）"],
    acceptance: ["每项题目要求都有能力项认领", "事实、假设和建议分开", "子问题、单位和硬约束完整"],
  },
  {
    id: "02-modeling",
    index: 2,
    title: "建模方案",
    shortTitle: "模型方案",
    status: "LOCKED",
    summary: "为每个子问题建立模型、假设、参数、算法和验证计划。",
    inputs: ["PROBLEM_ANALYSIS.md", "PROBLEM_FACTS.json", "CAPABILITY_CHECKLIST.json", "用户指定的思路和约束"],
    outputs: ["MODELING_REPORT.md", "MODEL_CONTRACT.json", "CROSS_PROBLEM_LEDGER.json"],
    acceptance: ["每项能力都有模型承接", "每问都有可编码的模型契约", "新增参数有来源或明确假设", "方向、单位和约束无未解释冲突"],
  },
  {
    id: "03-code",
    index: 3,
    title: "编程实现",
    shortTitle: "代码实现",
    status: "LOCKED",
    summary: "实现模型，并为每个子问题生成结构化结果。",
    inputs: ["MODEL_CONTRACT.json", "PROBLEM_FACTS.json", "DATA_PROFILE.json（若存在）", "用户数据与附件"],
    outputs: ["code/", "results/q*.json", "results/summary.json", "RESULTS.md", "DELIVERABLES.json"],
    acceptance: ["代码可从工作区根目录运行", "每个子问题都有结果文件", "结果含 run_id 和 config_hash", "失败断言未被吞掉", "RESULTS.md 不声称未实现的方法"],
  },
  {
    id: "04-validation",
    index: 4,
    title: "独立验证",
    shortTitle: "结果验证",
    status: "LOCKED",
    summary: "独立复算，并检查合理性、敏感性和多代结果。",
    inputs: ["code/", "results/", "MODEL_CONTRACT.json", "原始数据和题面约束"],
    outputs: ["validation/", "VALIDATION_REPORT.md", "RESULTS.md 中的审计凭证"],
    acceptance: ["硬约束经独立重算通过", "所有异常都有解释", "关键结论有验证证据", "没有旧代结果混入"],
  },
  {
    id: "05-figures",
    index: 5,
    title: "图表生成",
    shortTitle: "图表制作",
    status: "LOCKED",
    summary: "依据清单生成数据图、表格和示意图。",
    inputs: ["PROBLEM_ANALYSIS.md 中的图表需求", "MODEL_CONTRACT.json", "results/", "VALIDATION_REPORT.md"],
    outputs: ["FIGURE_MANIFEST.json", "figures/ 图表与源代码", "FIGURE_REPORT.md", "TABLE_DATA_CHECKLIST.md（适用时）"],
    acceptance: ["清单中的图表均有产物", "图中数字来自结果文件", "图表来源、单位和子问题一致", "缺少视觉检查时明确标记阻塞或降级"],
  },
  {
    id: "06-paper",
    index: 6,
    title: "论文写作",
    shortTitle: "论文撰写",
    status: "LOCKED",
    summary: "依据建模、验证和图表结果撰写论文与数据核对清单。",
    inputs: ["题目分析、建模报告、结果与验证报告", "figures/ 与 FIGURE_MANIFEST.json", "用户提供的论文模板（若有）"],
    outputs: ["paper/main.tex 或等价源文件", "paper/sections/（正文较长时）", "PAPER_DATA_CHECKLIST.md", "PAPER_REPORT.md"],
    acceptance: ["每个子问题都有模型、方法、结果和分析", "图表引用均存在", "没有占位符、旧代数字或未证实声称", "模拟数据没有冒充实测"],
  },
  {
    id: "07-compile",
    index: 7,
    title: "编译与渲染",
    shortTitle: "编译检查",
    status: "LOCKED",
    summary: "编译论文，渲染页面并检查源码与 PDF。",
    inputs: ["paper/ 源文件", "figures/", "用户模板和字体", "CAPABILITY_REPORT.json"],
    outputs: ["paper/main.pdf", "COMPILE_REPORT.md", "paper/main.log 或等价编译日志"],
    acceptance: ["PDF 可打开且不早于源文件", "没有致命编译错误", "图表和表格均已嵌入", "渲染检查未发现不可读或裁切"],
  },
  {
    id: "08-final-audit",
    index: 8,
    title: "最终验收",
    shortTitle: "最终审计",
    status: "LOCKED",
    summary: "汇总各阶段证据，并判断最终交付是否满足用户要求。",
    inputs: ["全部阶段产物", "STAGE_STATE.json", "CAPABILITY_REPORT.json", "用户要求"],
    outputs: ["FINAL_AUDIT.md", "EVIDENCE_INDEX.md", "更新后的 STAGE_STATE.json"],
    acceptance: ["必需阶段均无 FAIL 或 BLOCKED", "每条关键结论都有证据路径", "PDF、源文件和结果属于同一 run_id", "用户约束没有未确认偏离"],
  },
];
