import { createPinia } from "pinia";
import { createApp } from "vue";
import "@/assets/style.css";
import App from "@/App.vue";
import router from "@/router";
import { installArtifactEditChatDomPatch } from "@/utils/artifactEditChatDom";
import { installArtifactEditSelectionCleanupDomPatch } from "@/utils/artifactEditSelectionCleanupDom";
import { installChatAgentDuplicateDomPatch } from "@/utils/chatAgentDuplicateDom";
import { installChatArtifactLinkDomPatch } from "@/utils/chatArtifactLinkDom";
import { installChatChoiceCardDomPatch } from "@/utils/chatChoiceCardDom";
import { installChatPhaseDividerDomPatch } from "@/utils/chatPhaseDividerDom";
import { installCompactTimelineDomPatch } from "@/utils/compactTimelineDom";
import { installImageGalleryTitleDomPatch } from "@/utils/imageGalleryTitleDom";
import { installModelingDiscussionSync } from "@/utils/modelingDiscussionSync";
import { installPaperPreviewDomPatch } from "@/utils/paperPreviewDom";
import { installPaperPreviewLayoutDomPatch } from "@/utils/paperPreviewLayoutDom";
import { installPaperPreviewMathCleanupDomPatch } from "@/utils/paperPreviewMathCleanupDom";
import { installSmoothStreamingTextDomPatch } from "@/utils/smoothStreamingTextDom";
import { installTimelineWordingDomPatch } from "@/utils/timelineWordingDom";
import piniaPluginPersistedstate from "pinia-plugin-persistedstate";

const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
const app = createApp(App);

app.use(router);
app.use(pinia);
app.mount("#app");

installArtifactEditChatDomPatch();
installArtifactEditSelectionCleanupDomPatch();
installCompactTimelineDomPatch();
installTimelineWordingDomPatch(pinia);
installChatArtifactLinkDomPatch();
installImageGalleryTitleDomPatch();
installModelingDiscussionSync();
installChatPhaseDividerDomPatch();
installChatAgentDuplicateDomPatch();
installChatChoiceCardDomPatch();
installPaperPreviewDomPatch();
installPaperPreviewLayoutDomPatch();
installPaperPreviewMathCleanupDomPatch();
installSmoothStreamingTextDomPatch();
